#!/bin/sh

exec 2>&1
exec cockroach start \
  {{#if cfg.insecure ~}}
  --insecure \
  {{/if ~}}
  {{#if svc.me.follower ~}}
  --join={{svc.leader.sys.ip}}:{{svc.leader.cfg.port}} \
  {{/if ~}}
  --host={{sys.ip}} \
  --port={{cfg.port}} \
  --http-host={{sys.ip}} \
  --http-port={{cfg.http-port}} \
  --store={{pkg.svc_data_path}}
